name: DEBUG Validate Secrets
on:
  workflow_dispatch:

jobs:
  validate-access-token:
    name: Access
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      GH_TOKEN: ${{ secrets.GH_PAT }}
    outputs:
      HAS_WORKFLOW_PERMISSION: ${{ steps.access-token.outputs.has_workflow_permission }}
    steps:
      - name: DEBUG: Print GH_PAT Info
        run: |
          echo "Length of GH_PAT: ${#GH_PAT}"
          echo "Start: ${GH_PAT:0:4}****"
          echo "End:
