name: DEBUG Test GH_PAT
on:
  workflow_dispatch:

jobs:
  test-gh-pat:
    runs-on: macos-14
    steps:
      - name: Show partial GH_PAT
        shell: bash
        run: |
          echo "Token length: $(echo -n $GH_PAT | wc -c)"
          echo "First 4 chars: $(echo -n $GH_PAT | cut -c1-4)****"
          echo "Last 4 chars: ****$(echo -n $GH_PAT | rev | cut -c1-4 | rev)"
          curl -i -H "Authorization: token $GH_PAT" https://api.github.com

        env:
          GH_PAT: ${{ secrets.GH_PAT }}
